// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fm_compute_descriptor_operators_cpp
arma::cube fm_compute_descriptor_operators_cpp(const arma::mat& phi, const arma::mat& descriptors, SEXP measure);
RcppExport SEXP _fmapsR_fm_compute_descriptor_operators_cpp(SEXP phiSEXP, SEXP descriptorsSEXP, SEXP measureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type descriptors(descriptorsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type measure(measureSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_compute_descriptor_operators_cpp(phi, descriptors, measure));
    return rcpp_result_gen;
END_RCPP
}
// fm_match_value_grad_cpp
Rcpp::List fm_match_value_grad_cpp(const arma::mat& C, const arma::mat& A, const arma::mat& B, const arma::mat& ev_sqdiff, const arma::cube& op1_cube, const arma::cube& op2_cube, const arma::cube& op1_t_cube, const arma::cube& op2_t_cube, const double w_descr, const double w_lap, const double w_comm);
RcppExport SEXP _fmapsR_fm_match_value_grad_cpp(SEXP CSEXP, SEXP ASEXP, SEXP BSEXP, SEXP ev_sqdiffSEXP, SEXP op1_cubeSEXP, SEXP op2_cubeSEXP, SEXP op1_t_cubeSEXP, SEXP op2_t_cubeSEXP, SEXP w_descrSEXP, SEXP w_lapSEXP, SEXP w_commSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ev_sqdiff(ev_sqdiffSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_cube(op1_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_cube(op2_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_t_cube(op1_t_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_t_cube(op2_t_cubeSEXP);
    Rcpp::traits::input_parameter< const double >::type w_descr(w_descrSEXP);
    Rcpp::traits::input_parameter< const double >::type w_lap(w_lapSEXP);
    Rcpp::traits::input_parameter< const double >::type w_comm(w_commSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_match_value_grad_cpp(C, A, B, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm));
    return rcpp_result_gen;
END_RCPP
}
// fm_match_energy_terms_cpp
Rcpp::List fm_match_energy_terms_cpp(const arma::mat& C, const arma::mat& A, const arma::mat& B, const arma::mat& ev_sqdiff, const arma::cube& op1_cube, const arma::cube& op2_cube, const double w_descr, const double w_lap, const double w_comm);
RcppExport SEXP _fmapsR_fm_match_energy_terms_cpp(SEXP CSEXP, SEXP ASEXP, SEXP BSEXP, SEXP ev_sqdiffSEXP, SEXP op1_cubeSEXP, SEXP op2_cubeSEXP, SEXP w_descrSEXP, SEXP w_lapSEXP, SEXP w_commSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ev_sqdiff(ev_sqdiffSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_cube(op1_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_cube(op2_cubeSEXP);
    Rcpp::traits::input_parameter< const double >::type w_descr(w_descrSEXP);
    Rcpp::traits::input_parameter< const double >::type w_lap(w_lapSEXP);
    Rcpp::traits::input_parameter< const double >::type w_comm(w_commSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_match_energy_terms_cpp(C, A, B, ev_sqdiff, op1_cube, op2_cube, w_descr, w_lap, w_comm));
    return rcpp_result_gen;
END_RCPP
}
// fm_match_apply_operator_cpp
arma::mat fm_match_apply_operator_cpp(const arma::mat& C, const arma::mat& AAt, const arma::mat& ev_sqdiff, const arma::cube& op1_cube, const arma::cube& op2_cube, const arma::cube& op1_t_cube, const arma::cube& op2_t_cube, const double w_descr, const double w_lap, const double w_comm);
RcppExport SEXP _fmapsR_fm_match_apply_operator_cpp(SEXP CSEXP, SEXP AAtSEXP, SEXP ev_sqdiffSEXP, SEXP op1_cubeSEXP, SEXP op2_cubeSEXP, SEXP op1_t_cubeSEXP, SEXP op2_t_cubeSEXP, SEXP w_descrSEXP, SEXP w_lapSEXP, SEXP w_commSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type AAt(AAtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ev_sqdiff(ev_sqdiffSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_cube(op1_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_cube(op2_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_t_cube(op1_t_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_t_cube(op2_t_cubeSEXP);
    Rcpp::traits::input_parameter< const double >::type w_descr(w_descrSEXP);
    Rcpp::traits::input_parameter< const double >::type w_lap(w_lapSEXP);
    Rcpp::traits::input_parameter< const double >::type w_comm(w_commSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_match_apply_operator_cpp(C, AAt, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm));
    return rcpp_result_gen;
END_RCPP
}
// fm_match_solve_cg_cpp
Rcpp::List fm_match_solve_cg_cpp(const arma::mat& C0, const arma::mat& rhs, const arma::mat& AAt, const arma::mat& ev_sqdiff, const arma::cube& op1_cube, const arma::cube& op2_cube, const arma::cube& op1_t_cube, const arma::cube& op2_t_cube, const double w_descr, const double w_lap, const double w_comm, const arma::mat& diag_precond, const int maxit, const double tol);
RcppExport SEXP _fmapsR_fm_match_solve_cg_cpp(SEXP C0SEXP, SEXP rhsSEXP, SEXP AAtSEXP, SEXP ev_sqdiffSEXP, SEXP op1_cubeSEXP, SEXP op2_cubeSEXP, SEXP op1_t_cubeSEXP, SEXP op2_t_cubeSEXP, SEXP w_descrSEXP, SEXP w_lapSEXP, SEXP w_commSEXP, SEXP diag_precondSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type AAt(AAtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ev_sqdiff(ev_sqdiffSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_cube(op1_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_cube(op2_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op1_t_cube(op1_t_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type op2_t_cube(op2_t_cubeSEXP);
    Rcpp::traits::input_parameter< const double >::type w_descr(w_descrSEXP);
    Rcpp::traits::input_parameter< const double >::type w_lap(w_lapSEXP);
    Rcpp::traits::input_parameter< const double >::type w_comm(w_commSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type diag_precond(diag_precondSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fm_match_solve_cg_cpp(C0, rhs, AAt, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm, diag_precond, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// fm_nearest_neighbor_index_cpp
Rcpp::IntegerVector fm_nearest_neighbor_index_cpp(const arma::mat& reference, const arma::mat& query);
RcppExport SEXP _fmapsR_fm_nearest_neighbor_index_cpp(SEXP referenceSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(fm_nearest_neighbor_index_cpp(reference, query));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fmapsR_fm_compute_descriptor_operators_cpp", (DL_FUNC) &_fmapsR_fm_compute_descriptor_operators_cpp, 3},
    {"_fmapsR_fm_match_value_grad_cpp", (DL_FUNC) &_fmapsR_fm_match_value_grad_cpp, 11},
    {"_fmapsR_fm_match_energy_terms_cpp", (DL_FUNC) &_fmapsR_fm_match_energy_terms_cpp, 9},
    {"_fmapsR_fm_match_apply_operator_cpp", (DL_FUNC) &_fmapsR_fm_match_apply_operator_cpp, 10},
    {"_fmapsR_fm_match_solve_cg_cpp", (DL_FUNC) &_fmapsR_fm_match_solve_cg_cpp, 14},
    {"_fmapsR_fm_nearest_neighbor_index_cpp", (DL_FUNC) &_fmapsR_fm_nearest_neighbor_index_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fmapsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
