# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fm_compute_descriptor_operators_cpp <- function(phi, descriptors, measure) {
    .Call(`_fmapsR_fm_compute_descriptor_operators_cpp`, phi, descriptors, measure)
}

fm_match_value_grad_cpp <- function(C, A, B, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm) {
    .Call(`_fmapsR_fm_match_value_grad_cpp`, C, A, B, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm)
}

fm_match_energy_terms_cpp <- function(C, A, B, ev_sqdiff, op1_cube, op2_cube, w_descr, w_lap, w_comm) {
    .Call(`_fmapsR_fm_match_energy_terms_cpp`, C, A, B, ev_sqdiff, op1_cube, op2_cube, w_descr, w_lap, w_comm)
}

fm_match_apply_operator_cpp <- function(C, AAt, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm) {
    .Call(`_fmapsR_fm_match_apply_operator_cpp`, C, AAt, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm)
}

fm_match_apply_fixed_first_column_cpp <- function(fixed_value, AAt, ev_sqdiff, op1_cube, op2_cube, w_descr, w_lap, w_comm) {
    .Call(`_fmapsR_fm_match_apply_fixed_first_column_cpp`, fixed_value, AAt, ev_sqdiff, op1_cube, op2_cube, w_descr, w_lap, w_comm)
}

fm_match_solve_cg_cpp <- function(C0, rhs, AAt, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm, diag_precond, maxit, tol) {
    .Call(`_fmapsR_fm_match_solve_cg_cpp`, C0, rhs, AAt, ev_sqdiff, op1_cube, op2_cube, op1_t_cube, op2_t_cube, w_descr, w_lap, w_comm, diag_precond, maxit, tol)
}

fm_nearest_neighbor_index_cpp <- function(reference, query) {
    .Call(`_fmapsR_fm_nearest_neighbor_index_cpp`, reference, query)
}

